[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Redirect all API calls to the edge function
[[redirects]]
  from = "/api/geocoding/*"
  to = "/.netlify/functions/geocoding-proxy/:splat"
  status = 200

# Headers for the app
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), payment=()"