// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqfrfavebxlvthmqyivg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xZnJmYXZlYnhsdnRobXF5aXZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODg4MTUsImV4cCI6MjA2NTQ2NDgxNX0.KCPz6SM2KXug8AcuHHGuFkFvdz4pYrVnBXCig24GaPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);